set nocp
set number
set ruler
set laststatus=2
set autoread

execute pathogen#infect()
syntax on
filetype plugin indent on

autocmd vimenter * NERDTree

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

let g:nerdtree_tabs_open_on_console_startup=1
let g:nerdtree_tabs_focus_on_files=1

nmap , :tabprevious<CR> 
nmap . :tabnext<CR>
nmap / :tabnew<CR>
map <C-n> :NERDTreeFocusToggle<CR>
